import type { Food } from "@/types/food/food.type.ts";

export type NutrientFacts = {
  id: string;
  createdAt: string;
  changedAt: string | null;
  foodId: string;
  vitamin_a: number | null;
  vitamin_d: number | null;
  vitamin_e: number | null;
  vitamin_k: number | null;
  vitamin_c: number | null;
  vitamin_b1: number | null;
  vitamin_b2: number | null;
  vitamin_b3: number | null;
  vitamin_b5: number | null;
  vitamin_b6: number | null;
  vitamin_b7: number | null;
  vitamin_b9: number | null;
  vitamin_b12: number | null;
  choline: number | null;
  caffeine: number | null;
  calcium: number | null;
  phosphorus: number | null;
  magnesium: number | null;
  sodium: number | null;
  potassium: number | null;
  chloride: number | null;
  sulfur: number | null;
  iron: number | null;
  zinc: number | null;
  selenium: number | null;
  iodine: number | null;
  copper: number | null;
  manganese: number | null;
  chromium: number | null;
  molybdenum: number | null;
  fluoride: number | null;
  omega_3: number | null;
  omega_3_ala_mg: number | null;
  omega_3_epa_mg: number | null;
  omega_3_dha_mg: number | null;
  omega_6: number | null;
  omega_9: number | null;
  food?: Food;
};

export type CreateNutrientFactsRequest = Omit<NutrientFacts, "id" | "createdAt" | "changedAt" | "food">;
export type UpdateNutrientFactsRequest = Partial<CreateNutrientFactsRequest>;
