import type { HrvRecording } from "@/types/hrv/hrvRecording.type.ts";
import type { HrvWindow } from "@/types/hrv/hrvWindow.type.ts";

export type HrvMetrics = {
  id: string;
  createdAt: string;
  changedAt: string | null;
  mean_rr_ms: number | null;
  mean_hr_bpm: number | null;
  min_hr_bpm: number | null;
  max_hr_bpm: number | null;
  sdnn_ms: number | null;
  rmssd_ms: number | null;
  pnn50_percent: number | null;
  vlf_power: number | null;
  lf_power: number | null;
  hf_power: number | null;
  lf_hf_ratio: number | null;
  hf_peak_hz: number | null;
  rsa_bpm: number | null;
  sd1_ms: number | null;
  sd2_ms: number | null;
  baevsky_si: number | null;
  csi: number | null;
  cvi: number | null;
  sd1_sd2_ratio: number | null;
  sample_entropy: number | null;
  approx_entropy: number | null;
  dfa_alpha1: number | null;
  replaced_range: number | null;
  replaced_moving_average: number | null;
  replaced_adaptive: number | null;
  replaced_artifact_split: number | null;
  preserved_vagal_burst: number | null;
  preserved_pvc: number | null;
  merged_with_previous: boolean | null;
  artifact_merge_prev: number | null;
  preserved_tachy: number | null;
  artifact_total: number | null;
  artifact_percent: number | null;
  adaptiveFilteringApplied: boolean | null;
  rangeFilteringApplied: boolean | null;
  artifactFilteringApplied: boolean | null;
  movingAverageFilteringApplied: boolean | null;
  jump_count_100ms_200ms: number | null;
  jump_count_200ms_300ms: number | null;
  jump_count_300ms_400ms: number | null;
  jump_count_400ms_500ms: number | null;
  jump_count_500ms_600ms: number | null;
  jump_count_600ms_700ms: number | null;
  jump_count_700ms_800ms: number | null;
  jump_count_800ms_900ms: number | null;
  jump_count_900ms_1000ms: number | null;
  jump_count_1000ms: number | null;
  hrvRecordingId: string | null;
  hrvWindowId: string | null;
  hrvRecording?: HrvRecording | null;
  hrvWindow?: HrvWindow | null;
};

export type CreateHrvMetricsRequest = Omit<HrvMetrics, "id" | "createdAt" | "changedAt" | "hrvRecording" | "hrvWindow">;
export type UpdateHrvMetricsRequest = Partial<CreateHrvMetricsRequest>;
